spring:
  thymeleaf:
    cache: false
  datasource:
    name: dataSource
    url: jdbc:mysql://localhost/db_aty?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
artery:
  login:
    enabled: false
